---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-config
data:
  # Internal URLs
  AUTH_SERVICE_URL: "http://auth-service:5001"
  CHAT_SERVICE_URL: "http://chat-service:5002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5003"
  
  # Database Connections
  MONGO_URI_AUTH: "mongodb://mongodb:27017/auth_db"
  MONGO_URI_CHAT: "mongodb://mongodb:27017/chat_db"
  MONGO_URI_NOTIFICATION: "mongodb://mongodb:27017/notification_db"
  
  # Redis Connection
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # External Client URL (Update this when deploying with actual domain)
  CLIENT_URL: "http://44.206.53.131:3000"

---
apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
type: Opaque
stringData:
  # In a real production environment, change this to a strong random string
  JWT_SECRET: "supersecretkey"
