---
# Gateway Service (Exposed via LoadBalancer for AWS)
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer # Automatically provisions an AWS Classic or Network Load Balancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: prince093kumar/micro-chat-gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: AUTH_SERVICE_URL
            - name: CHAT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: CHAT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: NOTIFICATION_SERVICE_URL
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: CLIENT_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-app-secret
                  key: JWT_SECRET

---
# Client React App (Exposed via LoadBalancer for AWS)
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer # Automatically provisions an AWS Load Balancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: prince093kumar/micro-chat-client:latest
          ports:
            - containerPort: 80
